action_size: 17
batch_size: 1024
buffer_size: 50000
discrim_lr: 0.001
env_name: Craftax-Classic-Symbolic-v1

steps: 750000
save_freq: 100000
vis_freq: 50000
warmup_steps: 10000
rollouts_per_skill: 5

eps_decay: 0.999995
eps_start: 1.0
eps_end: 0.01

gamma: 0.9
policy_lr: 0.00001
skill_size: 5
state_size: 1345
tau: 0.0001
discrim_update_freq: 80
qlocal_update_freq: 80
qtarget_update_freq: 80
exp_type: mlp
discrim_units: 1024
policy_units: 1024
embedding_type: identity
embedding_size: 1345
device: cuda
save_checkpoints: true
dropout_rate: 0.2
num_envs: 10
gym_np: false