action_size: 27
batch_size: 256
buffer_size: 10000
discrim_lr: 0.01
discrim_momentum: 0.9
discrim_units: 128
env_name: CrafterReward-v1
episodes: 2000
eps_decay: 0.995
eps_end: 0.01
eps_start: 1.0
gamma: 0.99
max_steps_per_episode: 100
policy_lr: 0.001
policy_units: 128
skill_size: 5
state_size: [64, 64, 3]
tau: 0.001
update_every: 1
exp_type: mlp