action_size: 27
batch_size: 256
buffer_size: 10000
discrim_lr: 0.01
discrim_units: 128
env_name: CrafterReward-v1
episodes: 2000
eps_decay: 0.995
eps_end: 0.01
eps_start: 1.0
gamma: 0.99
policy_lr: 0.001
policy_units: 128
skill_size: 5
state_size: [64, 64, 3]
tau: 0.001
discrim_update_freq: 1
qlocal_update_freq: 1
qtarget_update_freq: 1
exp_type: mlp
embedding_type: identity
device: cuda
log_freq: 500
conv: true
num_envs: 5
save_checkpoints: true