action_size: 17
batch_size: 128
buffer_size: 10002
discrim_lr: 0.01
env_name: CraftaxClassicSymbolic

episodes: 500000
log_freq: 10000
warmup_steps: 10000

eps_decay: 0.999995
eps_start: 1.0
eps_end: 0.01

gamma: 0.7
policy_lr: 0.00001
skill_size: 5
state_size: 1345
tau: 0.0001
discrim_update_freq: 1
qlocal_update_freq: 1
qtarget_update_freq: 1
exp_type: mlp
discrim_units: 512
policy_units: 512
embedding_type: naive
embedding_size: 1345
device: cuda
save_checkpoints: true
dropout_rate: 0.2
num_envs: 5
gym_np: false