description: lunar_1h_s3 sweep
program: diayn.py
method: bayes
metric:
  goal: maximize
  name: I(z;s)
parameters:
  action_size:
    value: 4
  skill_size:
    value: 3
  state_size:
    value: 8
  embedding_size:
    value: 3
  batch_size:
    value: 128
  buffer_size:
    value: 10000
  env_name:
    value: LunarLander-v2
  exp_type:
    value: mlp
  conv:
    value: false
  embedding_type:
    value: 1h
  device:
    value: cuda
  eps_start:
    value: 1.0
  eps_end:
    value: 0.01
  steps:
    value: 500000
  log_freq:
    value: 50000
  discrim_units:
    value: 1024
  policy_units:
    value: 1024
  num_envs:
    value: 5
  save_freq:
    value: 100000000
  vis_freq:
    value: 100000
  warmup_steps:
    value: 5000
  dropout_rate:
    value: 0.2
  gym_np:
    value: true
  save_checkpoints:
    value: false
  
  eps_decay:
    values: [0.995, 0.9995, 0.99995, 0.999995]
  gamma:
    values: [0.9, 0.95, 0.99]
  policy_lr:
    values: [0.00001, 0.0001, 0.001, 0.01, 0.1]
  discrim_lr:
    values: [0.00001, 0.0001, 0.001, 0.01, 0.1]
  discrim_update_freq:
    values: [1, 2, 4, 8]
  qlocal_update_freq:
    values: [1, 2, 4, 8]
  qtarget_update_freq:
    values: [1, 2, 4, 8]
  tau:
    values: [0.01, 0.001, 0.0001]
