action_size: 4
batch_size: 128
buffer_size: 10000
discrim_lr: 0.0001
env_name: LunarLander-v2

steps: 500000
save_freq: 100000
vis_freq: 25000
warmup_steps: 5000

eps_decay: 0.999995
eps_start: 1.0
eps_end: 0.01

gamma: 0.9
policy_lr: 0.00001
skill_size: 3
state_size: 8
tau: 0.0001
discrim_update_freq: 1
qlocal_update_freq: 1
qtarget_update_freq: 1
exp_type: mlp
discrim_units: 512
policy_units: 512
embedding_type: identity
embedding_size: 8
device: cuda
conv: false
save_checkpoints: true
dropout_rate: 0.2
num_envs: 5
gym_np: true