action_size: 4
batch_size: 128
buffer_size: 10000
discrim_lr: 0.01
env_name: LunarLander-v2
episodes: 5000
eps_decay: 0.9995
eps_end: 0.01
eps_start: 1.0
gamma: 0.7
max_steps_per_episode: 300
policy_lr: 0.00001
skill_size: 5
state_size: 8
tau: 0.0001
discrim_update_freq: 1
qlocal_update_freq: 1
q_target_update_freq: 1
exp_type: mlp
discrim_units: 512
policy_units: 512
embedding_type: identity
embedding_size: 8
device: cuda
log_freq: 500