action_size: 4
batch_size: 1024
buffer_size: 10000
discrim_lr: 0.001
env_name: LunarLander-v2

steps: 500000
max_steps_per_ep: 1000
save_freq: 100000
vis_freq: 25000
warmup_steps: 0
save_rollouts: false
num_heads: 5
bootstrapped_dropout_prob: 0.5

eps_decay: 0.99995
eps_start: 1.0
eps_end: 0.01

gamma: 0.99
policy_lr: 0.001
skill_size: 3
state_size: 8
tau: 0.001
discrim_update_freq: 4
q_update_freq: 4
exp_type: mlp
discrim_units: 512
policy_units: 512
embedding_type: 1h
embedding_size: 3
device: cuda
conv: false
save_checkpoints: true
gym_np: true