action_size: 4
batch_size: 64
buffer_size: 10000
env_name: LunarLander-v2

steps: 500000
save_freq: 100000
vis_freq: 25000
warmup_steps: 5000

eps_decay: 0.99995
eps_start: 1.0
eps_end: 0.01

gamma: 0.99
policy_lr: 0.0005
state_size: 8
tau: 0.001
qlocal_update_freq: 4
qtarget_update_freq: 4
exp_type: mlp
policy_units: 512
device: cuda
conv: false
save_checkpoints: true
dropout_rate: 0.2
num_envs: 10
gym_np: true