action_size: 4
batch_size: 256
buffer_size: 10000
discrim_lr: 0.001
env_name: LunarLander-v2
episodes: 5000
eps_decay: 0.995
eps_end: 0.01
eps_start: 1.0
gamma: 0.95
policy_lr: 0.001
skill_size: 3
state_size: 8
tau: 0.01
discrim_update_freq: 1
qlocal_update_freq: 1
qtarget_update_freq: 1
discrim_reset_freq: 0
exp_type: mlp
discrim_units: 512
policy_units: 512
embedding_type: naive
embedding_size: 3
device: cuda
log_freq: 500
conv: false
num_envs: 5
save_checkpoints: true