name: metra_raw
skill_learning_method: metra
exp_type: mlp

# Training regime
steps: 2000000
warmup_steps: 10000
max_steps_per_ep: 1000
model_update_freq: 4
batch_size: 512
buffer_size: 50400

# METRA
metra_eps: 0.001
metra_lambda_init: 30.0

# Learning rates
discrim_lr: 0.0002
policy_lr: 0.0002

# Visualization
save_freq: 250000
vis_freq: 250000
rollouts_per_skill: 3
save_checkpoints: true
save_rollouts: true
vectorization: 100

# Reward shaping
reward_pr_coeff: 1.0
reward_gt_coeff: 0.0
reward_coeff_schedule: constant

# Exploration
eps_start: 1.0
eps_end: 0.1
eps_end_perc: 0.75

# Embedding
embedding_size: 1345
embedding_type: identity
skill_size: 5

# Other
discrim_units: 768
policy_units: 768
gamma: 0.99
tau: 0.001
device: cuda
gym_np: false

# Environment
env_name: Craftax-Classic-Symbolic-v1
state_size: 1345
action_size: 17
